CREATE DATABASE assur_auto;
USE assur_auto;

CREATE TABLE IF NOT EXISTS clients(
CL_ID INT NOT NULL PRIMARY KEY,
CL_NOM VARCHAR(30),
CL_PRENOM VARCHAR(20) NOT NULL,
CL_ADRESSE VARCHAR(100) NOT NULL,
CL_CODE_POSTAL CHAR(5) NOT NULL,
CL_VILLE VARCHAR(100) NOT NULL CHECK(CL_VILLE=CANNES),
CL_COORDONNEES VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS contrat(
CO_NUM INT NOT NULL PRIMARY KEY,
CO_DATE DATE NOT NULL,
CO_CATEGORIE VARCHAR(20) NOT NULL,
CL_ID_FK INT NOT NULL,
FOREIGN KEY(CL_ID_FK) REFERENCES clients(CL_ID)
);

INSERT INTO clients (CL_ID,CL_NOM,CL_PRENOM,CL_ADRESSE, CL_CODE_POSTAL, CL_VILLE, CL_COORDONNEES) VALUES
(1, 'DUPONT', 'JEAN', '2 RUE DE LA GARE', '06400', 'CANNES', '0655443322'),
(2, 'DUJARDIN','MARIE', '6 BOULEVARD CARNOT', '06400', 'CANNES', '0644332211');
  
INSERT INTO contrat (CO_NUM, CO_DATE, CO_CATEGORIE, CL_ID_FK) VALUES
(20, '2020-07-01','vehicule tourisme', 2),
(21, '2020-07-07','vehicule utilitaire', 1);





